### ISSUE TITLE
sudden streaming cut off 

### ISSUE THREAD

**Issue by omgbox** [KiraLT/torrent-stream-server#130]
is anybody experiencing sudden cut offs while streaming ? I'm not sure if this is something with herokuapp limits or the web torrent engine. the issue basically starts within few minutes after starting viewing the media.

**Comment by KiraLT** [comment]
Hello,

In some cases where the torrent is very popular (have many seeders), in a few minutes, you reach high download speed (on Heroku my torrent reached 50MB/s). And because of high speed, app CPU usage can reach maximum, and the whole app crash. You can monitor download speed on UI dashboard page. If download speed is higher than 10MB/s app can crash on Heroku. If it is very slow then you should find a more popular torrent. If you wondering how to control download speed, we have open issue for that: #15.

**Comment by KiraLT** [comment]
Closing this issue, if we encounter this issue even after completing #15, then we can reopen it.
