### ISSUE TITLE
NODE_ENV=development only on 127.0.0.1?

### ISSUE THREAD

**Issue by pataquets** [KiraLT/torrent-stream-server#159]
While setting up TSS behind a reverse proxy, I've set `NODE_ENV` to `development` for troubleshooting. I've seen this on logs, even I've set `HOST` to `0.0.0.0`:
https://github.com/KiraLT/torrent-stream-server/blob/86b82ad2175543faa5609de1d333f7135f29d86d/src/app.ts#L62

Is this message true or the string just needs to include listen address?

**Comment by KiraLT** [comment]
Main logging message prints correct host & URL:
> Listening on ${config.host}:${config.port}

But when you use `development` NODE_ENV, it also prints additional URLs. They mainly used for easy access while developing the system (so you could just click on the terminal and the link would be opened in the browser).

But we can't show `0.0.0.0` host, because it is not the actual host (it means that the server listens to all available IPs). That is why we show the localhost address. 

There is some logic show correct host when it is not `0.0.0.0`:
```js
logger.info(`* Website on http://${config.host === '0.0.0.0' ? '127.0.0.1' : config.host}:${config.port}`)
```
