### ISSUE TITLE
Heroku Site got Suspended

### ISSUE THREAD

**Issue by sheikh-haziq** [KiraLT/torrent-stream-server#163]
i published this project on heroku... it worked fine for one day but then suddenly my site got suuspended.

**Comment by KiraLT** [comment]
> Heroku forbids P2P services, so your account can be suspended ([learn more](https://github.com/KiraLT/torrent-stream-server/issues/32))

So there is the possibility that your account can be suspended, so you should use a free account with disposable email. If you get suspended, you can just create a new account.

Previously my account also got suspended, but I solved that issue already (where was one NPM dependency which Heroku blocked). I am running Heroku for a few months without any issue. 

There is a possibility, that your account can be suspended because #15 issue where download speed is not limited. On heroku it reaches up to 50MB/s and Heroku can detect high resource usage and suspend the app.

If you still get suspended with new accounts, I recommend choose [different deployment options](https://kiralt.github.io/torrent-stream-server/docs/setup) or wait for #15 task (there are finally movements from dependency).

**Comment by omgbox** [comment]
the deployment is working normally ,  you might have been red flagged by their signup bot. start clean with gmail. or trusted email services. even Microsoft mail services
