### ISSUE TITLE
Upload To Google Drive Directly

### ISSUE THREAD

**Issue by AyaanZaveri** [KiraLT/torrent-stream-server#171]
I've been using torrent-stream-server with Okteto and it's been working so great! Although, it would be great to have an upload to Google Drive button. Thanks!

**Comment by AyaanZaveri** [comment]
I tried to paste the url to the file into [this](https://softgateon.herokuapp.com/urltodrive/), but it only uploaded 50mb of the file. Although, rclone has a thing called [copyurl](https://rclone.org/commands/rclone_copyurl/) which could work.

**Comment by KiraLT** [comment]
Google drive has JavaScript library for that, I will try adding it:
https://developers.google.com/drive/api/v2/savetodrive

**Comment by AyaanZaveri** [comment]
Would that work with Shared/Team Drives?

**Comment by AyaanZaveri** [comment]
Did you find anything?

**Comment by KiraLT** [comment]
I added the button, but the upload is really slow. And if you exit page it will be canceled.

![download](https://user-images.githubusercontent.com/10944908/124027250-528e2c80-d9fb-11eb-8e51-9f3cc2aa8a4d.png)

**Comment by AyaanZaveri** [comment]
Looks great! Although, is there anyway to get team drive support.

**Comment by KiraLT** [comment]
Moved the upload screen to popup - because if you close it, the upload process will be canceled.

@AyaanZaveri I am not sure what did you mean about team drive support? If you talking about drive support from gsuite, you can select which account to use for uploading - so you can select gsuite account and upload to guite drive.

![Screenshot from 2021-09-14 19-19-47](https://user-images.githubusercontent.com/10944908/133295607-1baf86c1-4d13-49f8-8bfa-a9ce405be4a9.png)
