### ISSUE TITLE
MKV videos does not work on iOS

### ISSUE THREAD

**Issue by ShahmeerShahid** [KiraLT/torrent-stream-server#206]
When opening a stream on IOS, I get the following error:

![File_000](https://user-images.githubusercontent.com/37679657/127759657-7c09e88b-e289-4de0-ae97-9462df5b7df3.png)

The same page/stream works on OSX and Android.

**Comment by KiraLT** [comment]
The issue is because the browser doesn't support MKV files. Some browsers have experimental support (e.g. chrome), but they have limitations (like #16). To view MKV videos on devices that don't support MKV, you need a browser extension or open the video with an external player (like VLC). Most external players (on both PC and mobile) and play video from URL, so you just need copy stream URL.
