### ISSUE TITLE
Beware with Heroku deployments

### ISSUE THREAD

**Issue by pataquets** [KiraLT/torrent-stream-server#32]
Heroku terms forbid p2p:
https://www.heroku.com/policy/notices-and-license
My account has been suspended (when trying another p2p software).
I've had to go thru the unblock process and learnt it along the way.
Either place a warning or remove the Heroku button completely (the latter, the safer, IMO).

**Comment by KiraLT** [comment]
I also noticed, that Heroku automatically blocks some P2P services. Previously it also blocked this project, the culprit was [mafintosh/torrent-stream](https://github.com/mafintosh/torrent-stream).

Removing the Heroku button would be a shame because it's a very easy way to test this project. Plus Heroku doesn't block this project at the moment, I am running this project for a week and it works well. Moreover works well with a free tier and if it suspends the free tier it's now a bad thing. **But I recommend creating a new account for it.**

I added a warning below the button.

We should think about deployment alternatives. Heroku paid is quite expensive and doesn't support P2P. Maybe we should create a tutorial how to setup on VPS and suggest VPS provider.
