### ISSUE TITLE
Please apply advanced web video player | https://video-react.js.org

### ISSUE THREAD

**Issue by manikandan-kyyba** [KiraLT/torrent-stream-server#40]
Please apply advanced web video player like below open source.

> https://video-react.js.org

**Comment by KiraLT** [comment]
Hello,

What are the advantages of this player comparing with plain HTML? Also, why not [
Video.js](https://videojs.com) or [video-react](https://github.com/video-react/video-react)?

**Comment by manikandan-kyyba** [comment]
Hi @KiraLT 

Basically it's need all controls in web player, like

- Video Seek with timer
- Volume controll
- Video Poster Image
- Subtitle on/off
- Auto Play

finally also need **Mobile Support in website**

**Comment by KiraLT** [comment]
![Screenshot from 2020-11-24 00-24-05](https://user-images.githubusercontent.com/10944908/100022186-67fb0280-2deb-11eb-93e1-76b21ddaa305.png)

Added VideoJS player with a custom design. For the poster, it shows the first second of the video. Autoplay is disabled because it's annoying. Regarding subtitles, it supports only external subtitles. So we probably need integration for uploading subtitles, selecting from the torrent, or something like opensubtitles. MKV even if have subtitles, it won't work (check #16)
