### ISSUE TITLE
Heroku container and ffmpeg support

### ISSUE THREAD

**Issue by aditya-shri** [KiraLT/torrent-stream-server#62]
Its just an enhancement request. If it's possible, try to build it in the container stack with ubuntu layer before node layer so as to limit the ban if it happens. 
You might have to create heroku.yml file in it.

Also, if streaming can be through ffmpeg so multiple quality support can be added.

**Comment by KiraLT** [comment]
At the moment docker container uses NodeJS image. Do you think that Heroku scans image content and can find torrent dependencies in it? 

Regarding ffmpeg, I tried it before (to convert MKV to MP4). The issue was, that it needs stream from the start. So you lose skipping support (you can only watch video from the start without skipping anything).

**Comment by aditya-shri** [comment]
> At the moment docker container uses NodeJS image. Do you think that Heroku scans image content and can find torrent dependencies in it?

I have heard in other repos that even though heroku doesn't scan the image but it does scan the network means the type of data going in and out. That's why some aria based app gets suspended.

> Regarding ffmpeg, I tried it before (to convert MKV to MP4). The issue was, that it needs stream from the start. So you lose skipping support (you can only watch video from the start without skipping anything).
 Got it.
